version: '3.9'

networks:
  panel_lokatorski:
    driver: bridge
    ipam:
      config:
        - subnet: 172.57.0.0/16

volumes:
  redis_db_data:
    driver: local
  redisinsight_data:
    driver: local

services:
  httpd:
    container_name: ${DOCKER_DOMAIN}-httpd
    image: ${DOCKER_DOMAIN}-php:8.3-apache
    build:
      context: ./docker
      dockerfile: Dockerfile_Httpd
    volumes:
      - ./:/var/www/html/
    ports:
      - ${DOCKER_HTTPD_PORT}:80
    networks:
      - panel_lokatorski
    depends_on:
      - mysql

  mysql:
    container_name: ${DOCKER_DOMAIN}-mysql
    image: ${DOCKER_DOMAIN}-mysql:8.0.25
    build:
      context: ./docker
      dockerfile: Dockerfile_Mysql
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_SYSTEM_DIR-./mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    networks:
      - panel_lokatorski
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT}
      MYSQL_DATABASE: ${DOCKER_MYSQL_NAME}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASS}

  phpmyadmin:
    container_name: ${DOCKER_DOMAIN}-phpmyadmin
    image: ${DOCKER_DOMAIN}-phpmyadmin:5.2.1
    build:
      context: ./docker
      dockerfile: Dockerfile_PhpMyAdmin
    ports:
      - ${DOCKER_PHPMYADMIN_PORT}:80
    networks:
      - panel_lokatorski
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DOCKER_DOMAIN}-${DB_CONNECTION}
      - PAM_PORT=${DOCKER_MYSQL_PORT}
      - PMA_USER=${DOCKER_MYSQL_USER}
      - PMA_PASSWORD=${DOCKER_MYSQL_PASS}
    depends_on:
      - mysql

  maildev:
    container_name: ${DOCKER_DOMAIN}-maildev
    image: ${DOCKER_DOMAIN}-maildev/maildev

    build:
      context: ./docker
      dockerfile: Dockerfile_MailDev
    ports:
      - ${DOCKER_MAILCATCHER_SMTP}:1025
      - ${DOCKER_MAILCATCHER_WEB}:1080
    networks:
      - panel_lokatorski