FROM php:8.3-apache
LABEL authors=${DOCKER_AUTHOR}

RUN apt-get update -y
RUN apt-get install -y cron zip unzip
RUN docker-php-ext-install pdo pdo_mysql bcmath

RUN curl -sL https://deb.nodesource.com/setup_current.x | bash -
RUN apt-get install -y nodejs

WORKDIR /var/www/html

COPY ../. .
COPY php/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY php/php.ini /usr/local/etc/php/php.ini
COPY --from=composer:2.7.4 /usr/bin/composer /usr/bin/composer
COPY php/crontab /etc/cron.d/crontab

RUN chown -R www-data:www-data /var/www/html
RUN a2enmod rewrite
RUN crontab /etc/cron.d/crontab

ENTRYPOINT ["docker/php/entrypoint.sh"]
